In [3]:
import cv2
import numpy as np
from imblearn.under_sampling import EditedNearestNeighbours
from sklearn.model_selection import train_test_split #splitting the data into train and test
from sklearn.preprocessing import StandardScaler # standard preprocesing
from sklearn.neighbors import KNeighborsClassifier # Algorithm for knn
from sklearn.metrics import confusion_matrix #testing the model
from sklearn.metrics import f1_score #testing the model
from sklearn.metrics import accuracy_score #testing the model
import matplotlib.pyplot as plt
import pandas as pd
from cnn import condensed_nearest_neighbors
from sklearn.neighbors import NearestNeighbors

PATH = '/home/albertdipre/Desktop/MachineLearning/P2/frutas.jpeg'
image = cv2.imread(PATH)

# VISUALIZAR LA IMAGEN

# cv2.imshow("Frutas",image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()




In [4]:
#Muestras
#Fresas
Fresa = image[132:174,297:370,:]
# cv2.imshow("Fresa",Fresa)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
alto,ancho,canales = Fresa.shape
pixeles = Fresa.reshape(alto*ancho,canales)
fresa_DF = pd.DataFrame(pixeles,columns=['r','g','b'])
fresa_DF['clase']=0

print(fresa_DF)


Fresa2 = image[169:217,134:223,:]
# cv2.imshow("Fresa2",Fresa2)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
alto,ancho,canales = Fresa2.shape
pixeles = Fresa2.reshape(alto*ancho,canales)
fresa2_DF = pd.DataFrame(pixeles,columns=['r','g','b'])
fresa2_DF['clase']=0


Fresa3 = image[348:396,329:420,:]
# cv2.imshow("Fresa3",Fresa3)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
alto,ancho,canales = Fresa3.shape
pixeles = Fresa3.reshape(alto*ancho,canales)
fresa3_DF = pd.DataFrame(pixeles,columns=['r','g','b'])
fresa3_DF['clase']=0

        r    g    b  clase
0      48   26  155      0
1      38   11  144      0
2      81   54  188      0
3      76   46  183      0
4      45   11  152      0
...   ...  ...  ...    ...
3061   20    7   59      0
3062   10    0   48      0
3063   78   65  111      0
3064  129  118  156      0
3065   18   10   41      0

[3066 rows x 4 columns]


In [5]:
#Arandanos
Arandano = image[107:132,173:197,:]
# cv2.imshow("Fresa",Arandano)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
alto,ancho,canales = Arandano.shape
pixeles = Arandano.reshape(alto*ancho,canales)
Arandano_DF = pd.DataFrame(pixeles,columns=['r','g','b'])
Arandano_DF['clase']=1


Arandano2 = image[604:630,280:317,:]
# cv2.imshow("Fresa",Arandano2)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
alto,ancho,canales = Arandano2.shape
pixeles = Arandano2.reshape(alto*ancho,canales)
Arandano2_DF = pd.DataFrame(pixeles,columns=['r','g','b'])
Arandano2_DF['clase']=1



Arandano3 = image[353:373,46:86,:]
# cv2.imshow("Fresa",Arandano3)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
alto,ancho,canales = Arandano3.shape
pixeles = Arandano3.reshape(alto*ancho,canales)
Arandano3_DF = pd.DataFrame(pixeles,columns=['r','g','b'])
Arandano3_DF['clase']=1

In [6]:
#Cerezas
Cereza = image[423:474,301:353,:]
# cv2.imshow("Fresa",Cereza)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
alto,ancho,canales = Cereza.shape
pixeles = Cereza.reshape(alto*ancho,canales)
Cereza_DF = pd.DataFrame(pixeles,columns=['r','g','b'])
Cereza_DF['clase']=2

Cereza2= image[508:564,317:359,:]
# cv2.imshow("Fresa",Cereza2)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
alto,ancho,canales = Cereza2.shape
pixeles = Cereza2.reshape(alto*ancho,canales)
Cereza2_DF = pd.DataFrame(pixeles,columns=['r','g','b'])
Cereza2_DF['clase']=2


Cereza3= image[246:287,551:600,:]
# cv2.imshow("Fresa",Cereza3)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
alto,ancho,canales = Cereza3.shape
pixeles = Cereza3.reshape(alto*ancho,canales)
Cereza3_DF = pd.DataFrame(pixeles,columns=['r','g','b'])
Cereza3_DF['clase']=2

In [7]:
#Plato
Plato = image[0:23,2:547,:]
# cv2.imshow("Fresa",Plato)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
alto,ancho,canales = Plato.shape
pixeles = Plato.reshape(alto*ancho,canales)
Plato_DF = pd.DataFrame(pixeles,columns=['r','g','b'])
Plato_DF['clase']=3

Plato2 = image[715:735,1:500,:]
# cv2.imshow("Fresa",Plato2)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
alto,ancho,canales = Plato2.shape
pixeles = Plato2.reshape(alto*ancho,canales)
Plato2_DF = pd.DataFrame(pixeles,columns=['r','g','b'])
Plato2_DF['clase']=3



In [8]:
#Planta
Planta = image[676:,596:,:]
# cv2.imshow("Fresa",Planta)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
alto,ancho,canales = Planta.shape
pixeles = Planta.reshape(alto*ancho,canales)
Planta_DF = pd.DataFrame(pixeles,columns=['r','g','b'])
Planta_DF['clase']=4

Planta2 = image[4:46,606:,:]
# cv2.imshow("Fresa",Planta2)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

alto,ancho,canales = Planta2.shape
pixeles = Planta2.reshape(alto*ancho,canales)
Planta2_DF = pd.DataFrame(pixeles,columns=['r','g','b'])
Planta2_DF['clase']=4

In [9]:
DataConcatenada = pd.concat([fresa_DF,fresa2_DF,fresa3_DF,Arandano_DF,Arandano2_DF,Arandano3_DF,Cereza_DF,Cereza2_DF,Cereza3_DF,Plato_DF,Plato2_DF,Planta_DF,Planta2_DF],sort=False)
y = np.array(DataConcatenada)
XTESTEO = y[:,0:3]
y = y[:,3]
print(y.shape)

(47460,)


In [10]:
# Preparacion de los datos
x = DataConcatenada.drop('clase',axis =1)
y=DataConcatenada['clase']
X_train,X_test,Y_train,Y_test = train_test_split(x,y,random_state=0,test_size=0.2)
# Condensar la data
X_train = np.array(X_train)
Y_train = np.array(Y_train)
X_test = np.array(X_test)
Y_test = np.array(Y_test)
X_train,Y_train = condensed_nearest_neighbors(X_train,Y_train)



In [11]:
from math import sqrt 
print(sqrt(len(Y_test)))

97.4268956705488


In [12]:
classifer=KNeighborsClassifier(n_neighbors=97,p=2,metric='euclidean')
classifer.fit(X_train,Y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=97)

In [13]:
y_pred = classifer.predict(X_test)
y_pred

array([0, 3, 3, ..., 3, 3, 4])

In [14]:
cm = confusion_matrix(Y_test,y_pred)
print(cm)

[[2191    0  127   26   20]
 [   0  462    4    0    0]
 [  35    0 1332   26    0]
 [  32    0   17 4425    1]
 [   0    0    0    0  794]]


In [15]:
print(accuracy_score(Y_test,y_pred))


0.9696586599241467


In [16]:
score = f1_score(Y_test,y_pred,average='weighted')
print(score)

0.9697168375369059


In [17]:
def manhattan_dist(puntos, punto):
    return np.sum(np.abs(puntos - punto), axis=1)

In [18]:
def train_knn(X_train, Y_train, sample, k):
    distances = manhattan_dist(X_train, sample)
    indices = np.argsort(distances)
    Vecinos = [Y_train[j] for j in indices[:k]]

    # Clase mayoritaria entre los k vecinos más cercanos
    prediction = max(set(Vecinos), key=Vecinos.count) 
    return prediction


In [19]:
alto,ancho,canales = image.shape
IMAGENMODELADA = image.reshape((alto*ancho,canales))
df = pd.DataFrame(IMAGENMODELADA,columns=['r','g','b'])
print(df)

          r    g    b
0       205  221  214
1       216  232  225
2       215  232  229
3       203  222  219
4       200  218  219
...     ...  ...  ...
469563  116  118   58
469564   98  103   42
469565  106  113   52
469566  104  112   51
469567   75   86   24

[469568 rows x 3 columns]


In [20]:
X_test = df
y_pred = [train_knn(X_train,Y_train,sample,97) for sample in X_test.to_numpy()]
np.array(y_pred)


array([3, 3, 3, ..., 4, 4, 4])

In [21]:
#Reconstruyendo Imagen


# Asignar colores a cada clase (1 a 5)
colores_clases = {
    0: (86, 7, 12),  # Rosado
    1: (0, 0, 255),      # Azul
    2: (255, 0, 0),      # Rojo
    3:(0, 255, 0),
    4: (255, 255, 255) # Bl
}
Ancho = 736
alto = 638




In [22]:
colores_predichos = [colores_clases[prediccion] for prediccion in y_pred]
color_map = np.array(colores_predichos).reshape((Ancho,alto,canales))

imagen_color_map = cv2.imshow("Reconstruccion",color_map.astype(np.uint8))
cv2.waitKey(0)
cv2.destroyAllWindows()


qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/albertdipre/.local/lib/python3.10/site-packages/cv2/qt/plugins"


In [23]:
hori = np.concatenate((image,color_map),axis=1)
cv2.imshow("MMMM",hori)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.9.0) /io/opencv/modules/highgui/src/precomp.hpp:155: error: (-215:Assertion failed) src_depth != CV_16F && src_depth != CV_32S in function 'convertToShow'
