> KNN-PREDICT WETHER A PERSON WILL HAVE DIABETES OR NOT

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split #splitting the data into train and test
from sklearn.preprocessing import StandardScaler # standard preprocesing
from sklearn.neighbors import KNeighborsClassifier # Algorithm for knn
from sklearn.metrics import confusion_matrix #testing the model
from sklearn.metrics import f1_score #testing the model
from sklearn.metrics import accuracy_score #testing the model



In [2]:
dataset = pd.read_csv(r'C:\Users\alber\OneDrive - INTEC\LAB MACHINE LEARNING\P2\diabetes.csv')
print(len(dataset))
print(dataset.head())

768
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  


In [3]:
# Replace the missing or not acceptable values with NaN and after with the mean
zero_not_accepted = ['Glucose','BloodPressure','SkinThickness','BMI','Insulin']
for column in zero_not_accepted:
    dataset[column]=dataset[column].replace(0,np.NaN)
    mean = int(dataset[column].mean(skipna=True))
    dataset[column]= dataset[column].replace(np.NaN, mean)
    

In [4]:
print(dataset['Glucose'])

0      148.0
1       85.0
2      183.0
3       89.0
4      137.0
       ...  
763    101.0
764    122.0
765    121.0
766    126.0
767     93.0
Name: Glucose, Length: 768, dtype: float64


In [5]:
#Split dataset into train and test
X = dataset.iloc[:,0:8]
y = dataset.iloc[:,8]
X_train,X_test, y_train, y_test = train_test_split(X,y,random_state=0, test_size=0.2)#test size significa que cogeremos un 20% de la muestra en este caso y lo probaremos despues
print("Trained X \n",X_train,"\n","Test X \n",X_test,"\n","Trained y \n",y_train,"\n","test y \n",y_test)

Trained X 
      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
603            7    150.0           78.0           29.0    126.0  35.2   
118            4     97.0           60.0           23.0    155.0  28.2   
247            0    165.0           90.0           33.0    680.0  52.3   
157            1    109.0           56.0           21.0    135.0  25.2   
468            8    120.0           72.0           29.0    155.0  30.0   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0           76.0           48.0    180.0  32.9   
192            7    159.0           66.0           29.0    155.0  30.4   
629            4     94.0           65.0           22.0    155.0  24.7   
559           11     85.0           74.0           29.0    155.0  30.1   
684            5    136.0           82.0           29.0    155.0  32.0   

     DiabetesPedigreeFunction  Age  
603                     0.692   54  
118                     0

In [6]:
#Feature Scaling, lo estandariza para que toda la data este en el mismo rango en este caso de -1 a 1
sc_X= StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

print("Trained X \n",X_train)
print("Test X \n", X_test)


Trained X 
 [[ 0.90832902  0.93641795  0.44764174 ...  0.36863635  0.67740401
   1.69955804]
 [ 0.03644676 -0.81630913 -1.05200558 ... -0.63294341 -0.07049698
  -0.96569189]
 [-1.12606292  1.43247278  1.44740662 ...  2.81535261 -0.11855487
  -0.88240283]
 ...
 [ 0.03644676 -0.91552009 -0.63543688 ... -1.13373329 -0.95656442
  -1.04898095]
 [ 2.0708387  -1.21315299  0.11438678 ... -0.36108605 -0.50001442
   0.11706589]
 [ 0.32707418  0.47343344  0.7808967  ... -0.08922869  0.52121586
   2.94889395]]
Test X 
 [[-0.8354355   2.55686374  0.28101426 ...  1.47037408  2.78594417
  -0.96569189]
 [-0.54480808 -0.4856059   0.11438678 ...  0.13970383 -0.1876381
  -0.88240283]
 [ 0.03644676 -1.51078589 -0.8853781  ...  0.19693696 -0.22668514
  -0.71582471]
 ...
 [ 0.03644676  0.67185537  1.11415166 ...  1.62776519  0.53623395
  -0.96569189]
 [-0.25418066 -0.187973    0.11438678 ... -0.90480077 -1.07971278
  -0.79911377]
 [-0.8354355  -0.4856059  -0.0522407  ... -0.26092807  1.06487079
  -0.7991137

In [7]:
#Lenght'
import math as m
m.sqrt(len(y_test))

12.409673645990857

In [8]:
#Define the model: INIT K-NN
classifier = KNeighborsClassifier(n_neighbors=11,p=2,metric='euclidean')
classifier.fit(X_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=11)

In [9]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [10]:
#Evaluate the model
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[94 13]
 [15 32]]


In [11]:
print(f1_score(y_test,y_pred))

0.6956521739130435


In [12]:
#accuracy of the model
print(accuracy_score(y_test,y_pred)*100,"%")

81.81818181818183 %


In [16]:
import numpy as np

def euclidean_distance(x1, x2):
    """Compute the Euclidean distance between two points."""
    return np.sqrt(np.sum((x1 - x2)**2))

def condensed_nearest_neighbors(X, y):
    """Condensed Nearest Neighbors (CNN) algorithm."""
    condensed_X = [X[0]]  # Initialize condensed dataset with the first instance
    condensed_y = [y[0]]  # Corresponding labels

    for i in range(1, len(X)):
        x = X[i]
        label = y[i]

        # Check if the instance can be correctly classified by the condensed dataset
        classified_correctly = False
        for j in range(len(condensed_X)):
            if condensed_y[j] == label and euclidean_distance(x, condensed_X[j]) == 0:
                classified_correctly = True
                break
        
        # If not, add it to the condensed dataset
        if not classified_correctly:
            condensed_X.append(x)
            condensed_y.append(label)

    return np.array(condensed_X), np.array(condensed_y)

# Example usage:
# Generate some random data as a training set
np.random.seed(0)
X = np.random.rand(10000000, 2)
y = np.random.randint(0, 2, 10000000)

# Apply CNN
condensed_X, condensed_y = condensed_nearest_neighbors(X, y)

print("Original dataset size:", X.shape)
print("Condensed dataset size:", condensed_X.shape)


Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "C:\Users\alber\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\alber\AppData\Local\Temp\ipykernel_31140\1563511153.py", line 37, in <module>
    condensed_X, condensed_y = condensed_nearest_neighbors(X, y)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alber\AppData\Local\Temp\ipykernel_31140\1563511153.py", line -1, in condensed_nearest_neighbors
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alber\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py", line 2105, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alber\AppData\Roaming\Python\Python311\site-packages\IPython\core\ult

In [2]:
import numpy as np
import pandas as pd
from knn import KNN
# Define the Euclidean distance function
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

# Implement an optimized version of the Condensed Nearest Neighbors algorithm
def condensed_nearest_neighbors_optimized(X, y):
    S = [X[0]]  # Initialize the subset with the first instance
    S_labels = [y[0]]
    
    for i in range(1, len(X)):
        x_i = X[i]
        y_i = y[i]
        misclassified = True
        
        for j, s in enumerate(S):
            if S_labels[j] == y_i and np.array_equal(s, x_i):
                misclassified = False
                break
        
        if misclassified:
            S.append(x_i)
            S_labels.append(y_i)
    
    return np.array(S), np.array(S_labels)

# Sample dataset with 70,000 rows
X = np.random.rand(70000, 3)
y = np.random.randint(2, size=70000)

# Apply the CNN algorithm on the larger dataset
S, S_labels = condensed_nearest_neighbors_optimized(X, y)

print("Condensed dataset shape:", S.shape)
print("Unique labels in the condensed dataset:", np.unique(S_labels))




dataset = pd.read_excel(r"C:\Users\alber\OneDrive - INTEC\LAB MACHINE LEARNING\P2\knn_dataset.xlsx",sheet_name="Programming_exercise")
trainX = pd.read_excel(r"C:\Users\alber\OneDrive - INTEC\LAB MACHINE LEARNING\P2\knn_dataset.xlsx",sheet_name="Programming_exercise", usecols=[2,3,4])
trainY = pd.read_excel(r"C:\Users\alber\OneDrive - INTEC\LAB MACHINE LEARNING\P2\knn_dataset.xlsx",sheet_name="Programming_exercise", usecols=[1])
X_test = pd.read_excel(r"C:\Users\alber\OneDrive - INTEC\LAB MACHINE LEARNING\P2\knn_dataset.xlsx",sheet_name="Programming_exercise", usecols=[9,10,11])
Y_test = pd.read_excel(r"C:\Users\alber\OneDrive - INTEC\LAB MACHINE LEARNING\P2\knn_dataset.xlsx",sheet_name="Programming_exercise", usecols=[8])

trainX = np.array(trainX)
trainY = np.array(trainY)


S,S_labels = condensed_nearest_neighbors(trainX[1:,:],trainY[1:,:])
print(S.shape)
print(S_labels.shape)



KeyboardInterrupt: 

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset = pd.read_excel(r"C:\Users\alber\OneDrive - INTEC\LAB MACHINE LEARNING\P2\knn_dataset.xlsx",sheet_name="Programming_exercise")
trainX = pd.read_excel(r"C:\Users\alber\OneDrive - INTEC\LAB MACHINE LEARNING\P2\knn_dataset.xlsx",sheet_name="Programming_exercise", usecols=[2,3,4])
trainY = pd.read_excel(r"C:\Users\alber\OneDrive - INTEC\LAB MACHINE LEARNING\P2\knn_dataset.xlsx",sheet_name="Programming_exercise", usecols=[1])
X_test = pd.read_excel(r"C:\Users\alber\OneDrive - INTEC\LAB MACHINE LEARNING\P2\knn_dataset.xlsx",sheet_name="Programming_exercise", usecols=[9,10,11])
Y_test = pd.read_excel(r"C:\Users\alber\OneDrive - INTEC\LAB MACHINE LEARNING\P2\knn_dataset.xlsx",sheet_name="Programming_exercise", usecols=[8])

asda = np.array(X_test)
print(asda[1:20001,:])

[[178 98 0]
 [170 72 1]
 [157 60 0]
 ...
 [158 70 0]
 [185 75 1]
 [163 72 0]]
