1) Realice las transformaciones lineales (a) $q= Qx$ y (b) $x = Q^{-1}q$ donde

$$
Q = \begin{bmatrix} 
    5/6 & 1/6 & 0\\
    5/6 & 0 & 1/6\\
    0 & 5/6 & 1/6
    \end{bmatrix}
x = \begin{bmatrix}
    56\\
    14\\
    0.005 \end{bmatrix}
$$

In [13]:
import numpy as np
from fractions import Fraction
fr1 = Fraction(5,6)
fr2 = Fraction(1,6)
Matrix = [[fr1,fr2,0],[fr1,0,fr2],[0,fr1,fr2]]
Q = np.array(Matrix,dtype=float)

X = np.array([[56],[14],[0.005]])

#Realizando operacion a
q = np.matmul(Q,X)
q
#Realizando operacion b
x = np.matmul(np.linalg.inv(Q),q)
x
"""
    Observacion: Da exactamente igual multiplicar la inversa de Q por q a la matrix x 
    dado que solo se despejo la "x" de la operacion Qx =q
"""


'\n    Observacion: Da exactamente igual multiplicar la inversa de Q por q a la matrix x \n    dado que solo se despejo la "x" de la operacion Qx =q\n'

2) Importe los datos de un archivo .csv, .xls o .xlsx como una matrix a su plataforma preferida y despliegue las primeras 15 filas y 4 columnas

In [14]:
import pandas as pd 
import numpy as np

#IMPORTANDO DATOS DESDE EXCEL HASTA PYTHON

#MICROSOFT
# df = pd.read_excel(r"C:\Users\alber\OneDrive - INTEC\LAB MACHINE LEARNING\P1\Excel P1.xlsx")
#LINUX
df = pd.read_excel(r"/home/albertdipre/Desktop/MachineLearning/P1/Excel P1.xlsx")

print(df)
matriz = np.array(df)
matriz[:15,[0,1,2,3]]

    2  4  2.1  5  4.1  4.2
0   4  3    3  1    3    2
1   3  4    2  3    2    5
2   5  4    1  2    5    5
3   3  1    3  4    5    2
4   5  5    3  4    1    1
5   3  3    4  3    3    1
6   3  2    5  5    2    5
7   2  1    4  4    4    1
8   3  1    1  2    2    1
9   1  5    4  3    1    4
10  4  3    1  3    3    2
11  2  1    4  5    5    2
12  1  3    5  4    2    5
13  4  3    5  5    3    1
14  3  1    4  4    2    3
15  1  4    3  1    2    4
16  4  4    3  5    3    4
17  1  5    3  5    5    3
18  2  4    5  4    5    3
19  4  1    3  3    4    5
20  5  4    5  4    5    5
21  5  5    4  2    3    5
22  5  5    5  4    3    2
23  3  1    1  1    5    4


array([[4, 3, 3, 1],
       [3, 4, 2, 3],
       [5, 4, 1, 2],
       [3, 1, 3, 4],
       [5, 5, 3, 4],
       [3, 3, 4, 3],
       [3, 2, 5, 5],
       [2, 1, 4, 4],
       [3, 1, 1, 2],
       [1, 5, 4, 3],
       [4, 3, 1, 3],
       [2, 1, 4, 5],
       [1, 3, 5, 4],
       [4, 3, 5, 5],
       [3, 1, 4, 4]])

3) Cree un  nuevo vector columna x = [x^1,x^2,x^3...] y copie alli el contenido de los ultimos 20 elementos de la tercera columna de la matriz creada en el paso anterior
4) Cree un nuevo vector fila y = [y^1,y^2...], donde caada y^i ~ N(1.7,5) es un numero aleatorio segun la distribucion Gaussiana especificada.

In [15]:
import pandas as pd 
import numpy as np


matriz = np.array(df)
# print(matriz)
x = matriz[-20:,2].reshape(20,1) # seleccionando la tercera columna los ultimos 20 valores
print(x.shape)
#Creando distribucion gaussiana
y = np.random.normal(loc=1.7,scale=5,size=(1,5))


#Generando la matriz A = xy

A = np.matmul(x,y)
A = np.array(A)
print(A.shape)
a = A.reshape(100,1)

(20, 1)
(20, 5)


# II. VECTORIZANDO OPERACIONES.
1) Compute la suma de los elementos de cada columna de la matriz A.
2) Compute el promedio de lo elementos de cada columna de la matriz A. 
3) Compute la varianza de los elementos de cada columna de la matriz A,
4) Compute el vector media *a* a parir de los vectores fila de la matriz A.
5) Compute la distancia euclideana entre *a* y cada vector fila de la matriz A
6) Vectorice e implemente las siguientes combinaciones lineales. Asuma los valores de su preferencia $a_i, a_{ij}$ y los descriptores $x_i$
### A) 
$$
    z=a^{1} + \sum_{i=2}^{5} a^{i}x^{i} = a^{1}+a^{2}x^{2}+a^{3}x^{3}+...+a^{5}x^{5}
$$
### B) 
$$
z^{j}=a^{j1}+ \sum_{i=2}^{5} a^{ji}x^{i},j=1,2,3.
$$

In [16]:
import pandas as pd 
import numpy as np


matriz = np.array(df)
# print(matriz)
x = matriz[-20:,2].reshape(20,1) # seleccionando la tercera columna los ultimos 20 valores
print(x.shape)
#Creando distribucion gaussiana
y = np.random.normal(loc=1.7,scale=5,size=(1,5))


#Generando la matriz A = xy

A = np.matmul(x,y)
A = np.array(A)
a = A.reshape(100,1)

#Vectorizando las matrices
sumColumnas = np.sum(A, axis=1) #suma de columnas
meanColumnas = np.mean(A,axis=1) # promedio de cada columna
varianzaColumnas = np.var(A,axis=1) #Varianza de cada columna

meanFilas = np.mean(A,axis=0)
meanFilas.shape

distanciaEuclideana = np.linalg.norm(meanFilas - A, axis = 0)
distanciaEuclideana.shape

z=[];

M = np.array([[1,2,3],[4,5,6],[7,8,9]]).reshape(9,1)
x=np.linspace(1,12,12)
for i in range(2,6):
    Suma = M[1] + (np.dot(M[i],x[i]))
    z.append(Suma)
z = np.array(z)
z = np.sum(z)
print("Combinancion lineal inciso 6, z = \n",z)


# for j in range(3):
#     z[j] = a[j, 0] + np.sum(a[j, 1:] * x[1:])

# print(z)




(20, 1)
Combinancion lineal inciso 6, z = 
 94.0


ValueError: operands could not be broadcast together with shapes (0,) (11,) 

# III. Otras operaciones utiles
1) Aplique una funcion de slicing para extraer una matriz C de tamaño 4x4 a partir de las primeras 4 filas y 4 columnas de la matriz A. 
2) Compute la matriz de eigenvalues $\lambda$ y la matriz de eigenvectors V de la matriz de la matriz C. Regenere a $C = V \lambda V^{-1}$.
3) Lleve a cabo la operacion de singular value descomposition sobre las matrices A y C. Regenere las matrices A y C utilizando las matrices resultante de la composicion

In [ ]:
import pandas as pd
import numpy as np
from scipy.linalg import svd
df = pd.read_excel(r"C:\Users\alber\OneDrive - INTEC\LAB MACHINE LEARNING\P1\Excel P1.xlsx")
matriz = np.array(df)
# print(matriz)
x = matriz[-20:,2].reshape(20,1) # seleccionando la tercera columna los ultimos 20 valores
# print(x.shape)
#Creando distribucion gaussiana
y = np.random.normal(loc=1.7,scale=5,size=(1,5))


#Generando la matriz A = xy

A = np.matmul(x,y)
A = np.array(A)
print(A.shape)
#Slicing a 4x4 matrix from A
C = A[:4,:4]
C.shape

eigenvalues, eigenvectors = np.linalg.eig(C)

#print(eigenvalues.shape)
#print(eigenvectors.shape)

u = eigenvectors[:,1]
#print(u,"\n")
lam = eigenvalues[1]

#print(lam)
#print("\n",np.dot(C,u))

#print("\n", lam*u)

C = eigenvectors @ eigenvalues @ np.linalg.inv(eigenvectors)
#print(C.reshape(1,4))

C = A[:4,:4]
U_C, s_C, VT_C = svd(C)
U_A,s_A,VT_A = svd(A)

Sigma_A =np.zeros((A.shape[0],A.shape[1]))
# Sigma_C =np.zeros((A.shape[0],A.shape[1]))
Sigma_A[:A.shape[1], :A.shape[1]] = np.diag(s_A)
# print("mmm",Sigma_A.shape)
# Sigma_C[:C.shape[1], :C.shape[1]] = np.diag(s_C)

Sigma_C = np.diag(s_C)


#reconstruyendo matriz

reconstructionA = U_A @ Sigma_A @ VT_A
reconstructionC= U_C @ Sigma_C @ VT_C
print("U",U_C.shape,"s",s_C.shape, "VT", VT_C.shape)
print(C)
print(reconstructionC)

print(np.allclose(A,reconstructionA))

print(np.allclose(C,reconstructionC))


(20, 5)
U (4, 4) s (4,) VT (4, 4)
[[-17.17999803  -0.57950786  19.20653075 -21.69233023]
 [-22.90666403  -0.77267714  25.60870766 -28.92310697]
 [-28.63333004  -0.96584643  32.01088458 -36.15388371]
 [-22.90666403  -0.77267714  25.60870766 -28.92310697]]
[[-17.17999803  -0.57950786  19.20653075 -21.69233023]
 [-22.90666403  -0.77267714  25.60870766 -28.92310697]
 [-28.63333004  -0.96584643  32.01088458 -36.15388371]
 [-22.90666403  -0.77267714  25.60870766 -28.92310697]]
True
True
